language: node_js
node_js:
  - "7"
sudo: enabled

# Install headless chrome
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libdbus-1-3 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 fonts-liberation libappindicator1 libnss3 xdg-utils
  - wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P ~/
  - sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb

# Run the tests
script:
  - npm test
